version: '2.4'
services:
  ss:
    image: mritd/shadowsocks
    restart: always
    ports:
      - 443:443
    entrypoint:
      - ss-server
      - -c
      - /config.json
    volumes:
      - ./config.json:/config.json
